version: '3.9'
services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    env_file: .env

  rtmp:
    build: ./rtmp/
    ports:
      - '1935:1935'
      - '8080:8080'
    depends_on:
      - app
    volumes:
      - video_stream_data:/tmp/hls
      - ./rtmp:/etc/nginx

  rabbitmq_:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: 'exit 0'

  worker:
    build: ./worker
    volumes:
      - ./worker/:/worker
      - image_uploads:/worker/uploads
    depends_on:
      - rabbitmq_
    env_file: .env

  app:
    build: .
    volumes:
      - .:/app
      - image_uploads:/uploads
    ports:
      - '8000:3000'
    depends_on:
      - db
      - rabbitmq_
    env_file: .env

volumes:
  postgres_data:
  video_stream_data:
  image_uploads:
