version: '3.9'
services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    env_file: .env
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - '8000:3000'
    depends_on:
      - db
    env_file: .env
  rtmp:
    build: ./rtmp/
    ports:
      - '1935:1935'
      - '8080:8080'
    depends_on:
      - app
    volumes:
      - video_stream_data:/tmp/hls
      - ./rtmp:/etc/nginx

volumes:
  postgres_data:
  video_stream_data:
